FROM semapps/jena-fuseki-webacl

# Add missing package which may cause bugs
# See https://github.com/stain/jena-docker/issues/34#issuecomment-598138012
# RUN apt-get update && apt-get install -y --no-install-recommends procps
