version: '3.5'
services:
  traefik:
    image: traefik:v2.3
    container_name: traefik
    networks:
      - semapps
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=yannickduthe@hotmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  fuseki:
    build:
      context: ./fuseki
    container_name: fuseki
    networks:
      - semapps
    restart: always
    volumes:
      - ./fuseki/rdf_data:/fuseki
    ports:
      - "3030:3030"
    expose:
      - "3030"
    environment:
      ADMIN_PASSWORD: "admin"

  middleware-meta:
    build:
      context: middleware-meta
      args:
        - SELECTED_BRANCH=master
    container_name: middleware-meta
    networks:
      - semapps
    restart: always
    depends_on:
      - fuseki
    volumes:
      - ./meta/logs:/archipelago/middleware/logs
      - ./meta/actors:/archipelago/middleware/actors
      - ./meta/uploads:/archipelago/middleware/uploads
      - ./meta/jwt:/archipelago/middleware/jwt
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.middleware-meta.rule=Host(`data.meta.assemblee-virtuelle.org`)"
      - "traefik.http.routers.middleware-meta.entrypoints=websecure"
      - "traefik.http.routers.middleware-meta.tls.certresolver=myresolver"

  middleware-glocal:
    build:
      context: middleware-glocal
      args:
        - SELECTED_BRANCH=master
    container_name: middleware-glocal
    networks:
      - semapps
    restart: always
    depends_on:
      - fuseki
    volumes:
      - ./meta/logs:/archipelago/middleware/logs
      - ./meta/actors:/archipelago/middleware/actors
      - ./meta/uploads:/archipelago/middleware/uploads
      - ./meta/jwt:/archipelago/middleware/jwt
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.middleware-glocal.rule=Host(`data.gl.assemblee-virtuelle.org`)"
      - "traefik.http.routers.middleware-glocal.entrypoints=websecure"
      - "traefik.http.routers.middleware-glocal.tls.certresolver=myresolver"

  frontend-meta:
    build:
      context: ./frontend-meta
      args:
        - SELECTED_BRANCH=master
    container_name: frontend-meta
    ports:
      - "5000:5000"
    expose:
      - "5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-meta.rule=Host(`semapps.meta.assemblee-virtuelle.org`)"
      - "traefik.http.routers.frontend-meta.entrypoints=websecure"
      - "traefik.http.routers.frontend-meta.tls.certresolver=myresolver"

  frontend-glocal:
    build:
      context: ./frontend-glocal
      args:
        - SELECTED_BRANCH=master
    container_name: frontend-glocal
    ports:
      - "5001:5001"
    expose:
      - "5001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-glocal.rule=Host(`semapps.gl.assemblee-virtuelle.org`)"
      - "traefik.http.routers.frontend-glocal.entrypoints=websecure"
      - "traefik.http.routers.frontend-glocal.tls.certresolver=myresolver"

  redis:
    image: redis
    container_name: redis
    networks:
      - semapps
    volumes:
      - ./redis/data:/data
    expose:
      - "6379"
    command: ["redis-server", "--appendonly", "yes"]

networks:
  semapps:
    name: semapps_network
