version: '3.5'
services:
  traefik:
    image: traefik:v2.6.3
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=yannickduthe@hotmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  fuseki:
    build:
      context: ./fuseki
    container_name: fuseki
    restart: always
    volumes:
      - ./fuseki/rdf_data:/fuseki
    ports:
      - "3030:3030"
    expose:
      - "3030"
    environment:
      ADMIN_PASSWORD: "admin"

  # middleware-meta:
  #   build:
  #     context: middleware-meta
  #   container_name: middleware-meta
  #   restart: always
  #   depends_on:
  #     - fuseki
  #   volumes:
  #     - ./middleware-meta/logs:/archipelago/middleware/logs
  #     - ./middleware-meta/actors:/archipelago/middleware/actors
  #     - ./middleware-meta/uploads:/archipelago/middleware/uploads
  #     - ./middleware-meta/jwt:/archipelago/middleware/jwt
  #   expose:
  #     - "3000"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.middleware-meta.rule=Host(`data.meta.assemblee-virtuelle.org`)"
  #     - "traefik.http.routers.middleware-meta.entrypoints=websecure"
  #     - "traefik.http.routers.middleware-meta.tls.certresolver=myresolver"

  middleware-glocal:
    build:
      context: middleware-glocal
    container_name: middleware-glocal
    restart: always
    depends_on:
      - fuseki
    volumes:
      - ./middleware-glocal/logs:/archipelago/middleware/logs
      - ./middleware-glocal/actors:/archipelago/middleware/actors
      - ./middleware-glocal/uploads:/archipelago/middleware/uploads
      - ./middleware-glocal/jwt:/archipelago/middleware/jwt
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.middleware-glocal.rule=Host(`data.gl.assemblee-virtuelle.org`)"
      - "traefik.http.routers.middleware-glocal.entrypoints=websecure"
      - "traefik.http.routers.middleware-glocal.tls.certresolver=myresolver"

  # frontend-meta:
  #   build:
  #     context: ./frontend-meta
  #   container_name: frontend-meta
  #   expose:
  #     - "5000"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.frontend-meta.rule=Host(`semapps.meta.assemblee-virtuelle.org`)"
  #     - "traefik.http.routers.frontend-meta.entrypoints=websecure"
  #     - "traefik.http.routers.frontend-meta.tls.certresolver=myresolver"

  frontend-glocal:
    build:
      context: ./frontend-glocal
    container_name: frontend-glocal
    expose:
      - "5001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-glocal.rule=Host(`semapps.gl.assemblee-virtuelle.org`)"
      - "traefik.http.routers.frontend-glocal.entrypoints=websecure"
      - "traefik.http.routers.frontend-glocal.tls.certresolver=myresolver"

  redis:
    image: redis
    container_name: redis
    volumes:
      - ./redis/data:/data
    expose:
      - "6379"
    command: ["redis-server", "--appendonly", "yes"]
